name: Rust

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Set up Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
        - name: Check
          uses: actions-rs/cargo@v1
          with:
            command: check
        - name: Build Binary
          uses: actions-rs/cargo@v1
          with:
            command: build


